# ================================
# Docker Compose for RAG Chatbot
# ================================

version: '3.8'

services:
  backend:
    build: .
    container_name: rag-chatbot-backend
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_PORT=8000
    env_file:
      - .env
    volumes:
      - ./documents:/app/documents
    networks:
      - rag-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: node:18-alpine
    container_name: rag-chatbot-frontend
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - rag-network
    restart: unless-stopped
    command: >
      sh -c "npm install && npm start"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

networks:
  rag-network:
    driver: bridge

volumes:
  documents: